query UserOwnedProjects {
  user {
    id
    ownedProjects {
      id
      name
      type
      goal
      need
      description
      users {
        id
        image
        email
        name
      }
    }
  }
}
